[package]
name = "proxy"
version = "0.1.0"
edition = "2021"
authors = ["Unbreak4ble"]

[dependencies]
chrono = "0.4.26"
openssl = "0.10.56"
regex = "1.9.1"
spin = "0.9.8"
tokio = { version = "1", features = ["full"] }
